namespace DepartmentFinancialRecords.API.Models;
public class Student { public int Id{get;set;} public string StudentId{get;set;}=""; public string FullName{get;set;}=""; public string Course{get;set;}=""; public string YearLevel{get;set;}=""; public string Rfid{get;set;}=""; public string Status{get;set;}="Active"; }
public class User { public int Id{get;set;} public string Username{get;set;}=""; public string PasswordHash{get;set;}=""; public string Role{get;set;}="Staff"; }
public class AttendanceEvent { public int Id{get;set;} public string EventName{get;set;}=""; public DateTime EventDate{get;set;}=DateTime.Today; public string Location{get;set;}=""; }
public class AttendanceRecord { public int Id{get;set;} public int StudentId{get;set;} public int AttendanceEventId{get;set;} public DateTime CheckIn{get;set;}=DateTime.UtcNow; public string Status{get;set;}="Present"; public Student? Student{get;set;} public AttendanceEvent? AttendanceEvent{get;set;} }
public class Collection { public int Id{get;set;} public int StudentId{get;set;} public string CollectionType{get;set;}="Tuition"; public decimal Amount{get;set;} public string PaymentMethod{get;set;}="Cash"; public DateTime CollectionDate{get;set;}=DateTime.Today; public Student? Student{get;set;} }
public class Collectible { public int Id{get;set;} public int StudentId{get;set;} public string Description{get;set;}=""; public decimal AmountDue{get;set;} public DateTime DueDate{get;set;}=DateTime.Today; public string Status{get;set;}="Open"; public Student? Student{get;set;} }
public class Fine { public int Id{get;set;} public int StudentId{get;set;} public string Reason{get;set;}=""; public decimal Amount{get;set;} public bool IsPaid{get;set;} public Student? Student{get;set;} }
public class FundTransaction { public int Id{get;set;} public string TransactionType{get;set;}="Income"; public string Description{get;set;}=""; public decimal Amount{get;set;} public DateTime TransactionDate{get;set;}=DateTime.Today; }
public class Disbursement { public int Id{get;set;} public string Payee{get;set;}=""; public string Purpose{get;set;}=""; public decimal Amount{get;set;} public DateTime DisbursementDate{get;set;}=DateTime.Today; public string Status{get;set;}="Pending"; }
public class ActivityLog { public int Id{get;set;} public int UserId{get;set;} public string Action{get;set;}=""; public DateTime CreatedAt{get;set;}=DateTime.UtcNow; public User? User{get;set;} }
