using MySqlConnector;
using SBCCashier.Web.Models;
namespace SBCCashier.Web.Services;
public sealed class CashierStore
{
 private readonly string _cs;
 public CashierStore(IConfiguration config){_cs=config.GetConnectionString("DefaultConnection")??"Server=localhost;Port=3306;Database=sbccashier;User=root;Password=higanbana;";EnsureSchema();}
 private MySqlConnection Open(){var c=new MySqlConnection(_cs);c.Open();return c;}
 private void EnsureSchema(){var b=new MySqlConnectionStringBuilder(_cs);var db=b.Database;b.Database="";using(var s=new MySqlConnection(b.ConnectionString)){s.Open();using var q=s.CreateCommand();q.CommandText=$"CREATE DATABASE IF NOT EXISTS `{db}`";q.ExecuteNonQuery();}using var c=Open();using var q2=c.CreateCommand();q2.CommandText=@"CREATE TABLE IF NOT EXISTS Students(Id INT AUTO_INCREMENT PRIMARY KEY,StudentId VARCHAR(60) NOT NULL UNIQUE,FullName VARCHAR(180) NOT NULL,Course VARCHAR(160),YearLevel VARCHAR(40),Status VARCHAR(30) NOT NULL DEFAULT 'Active'); CREATE TABLE IF NOT EXISTS Payments(Id INT AUTO_INCREMENT PRIMARY KEY,StudentKey INT NOT NULL,PaymentType VARCHAR(60) NOT NULL,Description VARCHAR(240),Amount DECIMAL(12,2) NOT NULL,PaymentMethod VARCHAR(30) NOT NULL,ReferenceNumber VARCHAR(100),PaymentDate DATE NOT NULL,FOREIGN KEY(StudentKey) REFERENCES Students(Id)); CREATE TABLE IF NOT EXISTS RegistrarRequests(Id INT AUTO_INCREMENT PRIMARY KEY,StudentKey INT NOT NULL,DocumentType VARCHAR(60) NOT NULL,Purpose VARCHAR(240),Fee DECIMAL(12,2) NOT NULL,Status VARCHAR(30) NOT NULL,RequestedDate DATE NOT NULL,FOREIGN KEY(StudentKey) REFERENCES Students(Id)); CREATE TABLE IF NOT EXISTS VehiclePasses(Id INT AUTO_INCREMENT PRIMARY KEY,StudentKey INT NOT NULL,PlateNumber VARCHAR(60) NOT NULL,VehicleType VARCHAR(60) NOT NULL,Amount DECIMAL(12,2) NOT NULL,PaymentMethod VARCHAR(30) NOT NULL,Status VARCHAR(30) NOT NULL,IssuedDate DATE NOT NULL,FOREIGN KEY(StudentKey) REFERENCES Students(Id));";q2.ExecuteNonQuery();}
 public IReadOnlyList<Student> Students{get{using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT Id,StudentId,FullName,Course,YearLevel,Status FROM Students ORDER BY FullName";using var r=q.ExecuteReader();var x=new List<Student>();while(r.Read())x.Add(new Student{Id=r.GetInt32(0),StudentId=r.GetString(1),FullName=r.GetString(2),Course=r.IsDBNull(3)?"":r.GetString(3),YearLevel=r.IsDBNull(4)?"":r.GetString(4),Status=r.GetString(5)});return x;}}
 public IReadOnlyList<PaymentRow> Payments{get{using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT p.Id,p.StudentKey,p.PaymentType,p.Description,p.Amount,p.PaymentMethod,p.ReferenceNumber,p.PaymentDate,s.FullName,s.StudentId FROM Payments p JOIN Students s ON s.Id=p.StudentKey ORDER BY p.PaymentDate DESC,p.Id DESC";using var r=q.ExecuteReader();var x=new List<PaymentRow>();while(r.Read())x.Add(new PaymentRow{Id=r.GetInt32(0),StudentKey=r.GetInt32(1),PaymentType=r.GetString(2),Description=r.IsDBNull(3)?"":r.GetString(3),Amount=r.GetDecimal(4),PaymentMethod=r.GetString(5),ReferenceNumber=r.IsDBNull(6)?"":r.GetString(6),PaymentDate=r.GetDateTime(7),StudentName=r.GetString(8),StudentId=r.GetString(9)});return x;}}
 public IReadOnlyList<RequestRow> RegistrarRequests{get{using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT r.Id,r.StudentKey,r.DocumentType,r.Purpose,r.Fee,r.Status,r.RequestedDate,s.FullName,s.StudentId FROM RegistrarRequests r JOIN Students s ON s.Id=r.StudentKey ORDER BY r.RequestedDate DESC,r.Id DESC";using var reader=q.ExecuteReader();var x=new List<RequestRow>();while(reader.Read())x.Add(new RequestRow{Id=reader.GetInt32(0),StudentKey=reader.GetInt32(1),DocumentType=reader.GetString(2),Purpose=reader.IsDBNull(3)?"":reader.GetString(3),Fee=reader.GetDecimal(4),Status=reader.GetString(5),RequestedDate=reader.GetDateTime(6),StudentName=reader.GetString(7),StudentId=reader.GetString(8)});return x;}}
 public IReadOnlyList<VehiclePassRow> VehiclePasses{get{using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT v.Id,v.StudentKey,v.PlateNumber,v.VehicleType,v.Amount,v.PaymentMethod,v.Status,v.IssuedDate,s.FullName,s.StudentId FROM VehiclePasses v JOIN Students s ON s.Id=v.StudentKey ORDER BY v.IssuedDate DESC,v.Id DESC";using var r=q.ExecuteReader();var x=new List<VehiclePassRow>();while(r.Read())x.Add(new VehiclePassRow{Id=r.GetInt32(0),StudentKey=r.GetInt32(1),PlateNumber=r.GetString(2),VehicleType=r.GetString(3),Amount=r.GetDecimal(4),PaymentMethod=r.GetString(5),Status=r.GetString(6),IssuedDate=r.GetDateTime(7),StudentName=r.GetString(8),StudentId=r.GetString(9)});return x;}}
 public void AddStudent(Student x){using var c=Open();using var q=c.CreateCommand();q.CommandText="INSERT INTO Students(StudentId,FullName,Course,YearLevel,Status) VALUES(@id,@name,@course,@year,@status)";q.Parameters.AddWithValue("@id",x.StudentId.Trim());q.Parameters.AddWithValue("@name",x.FullName.Trim());q.Parameters.AddWithValue("@course",x.Course);q.Parameters.AddWithValue("@year",x.YearLevel);q.Parameters.AddWithValue("@status",x.Status);q.ExecuteNonQuery();}
 public void AddPayment(Payment x){using var c=Open();using var q=c.CreateCommand();q.CommandText="INSERT INTO Payments(StudentKey,PaymentType,Description,Amount,PaymentMethod,ReferenceNumber,PaymentDate) VALUES(@student,@type,@description,@amount,@method,@reference,CURDATE())";q.Parameters.AddWithValue("@student",x.StudentKey);q.Parameters.AddWithValue("@type",x.PaymentType);q.Parameters.AddWithValue("@description",x.Description);q.Parameters.AddWithValue("@amount",x.Amount);q.Parameters.AddWithValue("@method",x.PaymentMethod);q.Parameters.AddWithValue("@reference",x.ReferenceNumber);q.ExecuteNonQuery();}
 public void AddRequest(RegistrarRequest x){using var c=Open();using var q=c.CreateCommand();q.CommandText="INSERT INTO RegistrarRequests(StudentKey,DocumentType,Purpose,Fee,Status,RequestedDate) VALUES(@student,@type,@purpose,@fee,'Pending',CURDATE())";q.Parameters.AddWithValue("@student",x.StudentKey);q.Parameters.AddWithValue("@type",x.DocumentType);q.Parameters.AddWithValue("@purpose",x.Purpose);q.Parameters.AddWithValue("@fee",x.Fee);q.ExecuteNonQuery();}
 public void AddVehiclePass(VehiclePass x){using var c=Open();using var q=c.CreateCommand();q.CommandText="INSERT INTO VehiclePasses(StudentKey,PlateNumber,VehicleType,Amount,PaymentMethod,Status,IssuedDate) VALUES(@student,@plate,@type,@amount,@method,'Active',CURDATE())";q.Parameters.AddWithValue("@student",x.StudentKey);q.Parameters.AddWithValue("@plate",x.PlateNumber);q.Parameters.AddWithValue("@type",x.VehicleType);q.Parameters.AddWithValue("@amount",x.Amount);q.Parameters.AddWithValue("@method",x.PaymentMethod);q.ExecuteNonQuery();}
 public void MarkRequestReleased(int id){using var c=Open();using var q=c.CreateCommand();q.CommandText="UPDATE RegistrarRequests SET Status='Released' WHERE Id=@id";q.Parameters.AddWithValue("@id",id);q.ExecuteNonQuery();}
}
