using MySqlConnector;
using SCSDS.Web.Models;
namespace SCSDS.Web.Services;
public sealed class SCSDSStore
{
 private readonly string _cs;
 public SCSDSStore(IConfiguration c){var cs=c.GetConnectionString("DefaultConnection")??"Server=localhost;Port=3306;Database=scsds;User=root;Password=higanbana;";var password=Environment.GetEnvironmentVariable("DB_PASSWORD");if(!string.IsNullOrWhiteSpace(password))cs=new MySqlConnectionStringBuilder(cs){Password=password}.ConnectionString;_cs=cs;EnsureSchema();}
 private MySqlConnection Open(){var c=new MySqlConnection(_cs);c.Open();return c;}
 private void EnsureSchema(){var b=new MySqlConnectionStringBuilder(_cs);var db=b.Database;b.Database="";using(var s=new MySqlConnection(b.ConnectionString)){s.Open();using var q=s.CreateCommand();q.CommandText=$"CREATE DATABASE IF NOT EXISTS `{db}`";q.ExecuteNonQuery();}using var c=Open();using var q2=c.CreateCommand();q2.CommandText=@"CREATE TABLE IF NOT EXISTS Students(StudentId INT AUTO_INCREMENT PRIMARY KEY,StudentNumber VARCHAR(60) NOT NULL UNIQUE,StudentName VARCHAR(180) NOT NULL,Program VARCHAR(160),YearLevel VARCHAR(40),Status VARCHAR(30) NOT NULL DEFAULT 'Active');CREATE TABLE IF NOT EXISTS Products(ProductId INT AUTO_INCREMENT PRIMARY KEY,ProductName VARCHAR(160) NOT NULL,UnitPrice DECIMAL(12,2) NOT NULL,StockQuantity INT NOT NULL);CREATE TABLE IF NOT EXISTS Purchases(PurchaseId INT AUTO_INCREMENT PRIMARY KEY,StudentId INT NOT NULL,ProductId INT NOT NULL,Quantity INT NOT NULL,PurchaseDate DATE NOT NULL,Subtotal DECIMAL(12,2) NOT NULL,DiscountRate DECIMAL(5,4) NOT NULL,DiscountAmount DECIMAL(12,2) NOT NULL,TotalAmount DECIMAL(12,2) NOT NULL,FOREIGN KEY(StudentId) REFERENCES Students(StudentId),FOREIGN KEY(ProductId) REFERENCES Products(ProductId));";q2.ExecuteNonQuery();}
 public IReadOnlyList<Student> Students{get{using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT StudentId,StudentNumber,StudentName,Program,YearLevel,Status FROM Students ORDER BY StudentName";using var r=q.ExecuteReader();var x=new List<Student>();while(r.Read())x.Add(new Student{StudentId=r.GetInt32(0),StudentNumber=r.GetString(1),StudentName=r.GetString(2),Program=r.IsDBNull(3)?"":r.GetString(3),YearLevel=r.IsDBNull(4)?"":r.GetString(4),Status=r.GetString(5)});return x;}}
 public IReadOnlyList<Product> Products{get{using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT ProductId,ProductName,UnitPrice,StockQuantity FROM Products ORDER BY ProductName";using var r=q.ExecuteReader();var x=new List<Product>();while(r.Read())x.Add(new Product{ProductId=r.GetInt32(0),ProductName=r.GetString(1),UnitPrice=r.GetDecimal(2),StockQuantity=r.GetInt32(3)});return x;}}
 public IReadOnlyList<PurchaseRow> Purchases{get{using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT p.PurchaseId,p.StudentId,p.ProductId,p.Quantity,p.PurchaseDate,p.Subtotal,p.DiscountRate,p.DiscountAmount,p.TotalAmount,s.StudentName,s.StudentNumber,pr.ProductName FROM Purchases p JOIN Students s ON s.StudentId=p.StudentId JOIN Products pr ON pr.ProductId=p.ProductId ORDER BY p.PurchaseDate DESC,p.PurchaseId DESC";using var r=q.ExecuteReader();var x=new List<PurchaseRow>();while(r.Read())x.Add(new PurchaseRow{PurchaseId=r.GetInt32(0),StudentId=r.GetInt32(1),ProductId=r.GetInt32(2),Quantity=r.GetInt32(3),PurchaseDate=r.GetDateTime(4),Subtotal=r.GetDecimal(5),DiscountRate=r.GetDecimal(6),DiscountAmount=r.GetDecimal(7),TotalAmount=r.GetDecimal(8),StudentName=r.GetString(9),StudentNumber=r.GetString(10),ProductName=r.GetString(11)});return x;}}
 public decimal CalculateDiscountRate(decimal subtotal,bool active)=>!active?0m:subtotal>=500?0.15m:subtotal>=200?0.10m:subtotal>=100?0.05m:0m;
 public void AddStudent(Student x){using var c=Open();using var q=c.CreateCommand();q.CommandText="INSERT INTO Students(StudentNumber,StudentName,Program,YearLevel,Status) VALUES(@number,@name,@program,@year,@status)";q.Parameters.AddWithValue("@number",x.StudentNumber.Trim());q.Parameters.AddWithValue("@name",x.StudentName.Trim());q.Parameters.AddWithValue("@program",x.Program);q.Parameters.AddWithValue("@year",x.YearLevel);q.Parameters.AddWithValue("@status",x.Status);q.ExecuteNonQuery();}
 public void AddProduct(Product x){using var c=Open();using var q=c.CreateCommand();q.CommandText="INSERT INTO Products(ProductName,UnitPrice,StockQuantity) VALUES(@name,@price,@stock)";q.Parameters.AddWithValue("@name",x.ProductName.Trim());q.Parameters.AddWithValue("@price",x.UnitPrice);q.Parameters.AddWithValue("@stock",x.StockQuantity);q.ExecuteNonQuery();}
 public void CreatePurchase(int studentId,int productId,int quantity,DateTime date){using var c=Open();using var tx=c.BeginTransaction();using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="SELECT s.Status,pr.UnitPrice,pr.StockQuantity FROM Students s CROSS JOIN Products pr WHERE s.StudentId=@student AND pr.ProductId=@product FOR UPDATE";q.Parameters.AddWithValue("@student",studentId);q.Parameters.AddWithValue("@product",productId);using var r=q.ExecuteReader();if(!r.Read())throw new InvalidOperationException("Select a student and product.");var active=r.GetString(0).Equals("Active",StringComparison.OrdinalIgnoreCase);var price=r.GetDecimal(1);var stock=r.GetInt32(2);r.Close();if(quantity<1)throw new InvalidOperationException("Quantity must be at least 1.");if(stock<quantity)throw new InvalidOperationException("Not enough product stock.");var subtotal=price*quantity;var rate=CalculateDiscountRate(subtotal,active);var discount=Math.Round(subtotal*rate,2);using var add=c.CreateCommand();add.Transaction=tx;add.CommandText="INSERT INTO Purchases(StudentId,ProductId,Quantity,PurchaseDate,Subtotal,DiscountRate,DiscountAmount,TotalAmount) VALUES(@student,@product,@quantity,@date,@subtotal,@rate,@discount,@total);UPDATE Products SET StockQuantity=StockQuantity-@quantity WHERE ProductId=@product";add.Parameters.AddWithValue("@student",studentId);add.Parameters.AddWithValue("@product",productId);add.Parameters.AddWithValue("@quantity",quantity);add.Parameters.AddWithValue("@date",date.Date);add.Parameters.AddWithValue("@subtotal",subtotal);add.Parameters.AddWithValue("@rate",rate);add.Parameters.AddWithValue("@discount",discount);add.Parameters.AddWithValue("@total",subtotal-discount);add.ExecuteNonQuery();tx.Commit();}
 public void DeleteStudent(int id){using var c=Open();using var q=c.CreateCommand();q.CommandText="DELETE FROM Students WHERE StudentId=@id AND NOT EXISTS(SELECT 1 FROM Purchases WHERE StudentId=@id)";q.Parameters.AddWithValue("@id",id);q.ExecuteNonQuery();}
 public void DeleteProduct(int id){using var c=Open();using var q=c.CreateCommand();q.CommandText="DELETE FROM Products WHERE ProductId=@id AND NOT EXISTS(SELECT 1 FROM Purchases WHERE ProductId=@id)";q.Parameters.AddWithValue("@id",id);q.ExecuteNonQuery();}
}
